name: Create release

on: push
# if it's not ci skip, it'll trigger maven release, which will bump the version

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout out repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Create Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          maven-args: "-DskipTests"
          # todo: change this to master later
          release-branch-name: "build_workflow"
          version-minor: true
          skip-perform: true
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}